const crypto=require('crypto');
const nodemailer=require('nodemailer');
const Stripe=require('stripe');

const TOURS=[
 {id:'sintra',price:75,duration:'8 h',name:{en:'Sintra, Cabo da Roca & Cascais',pt:'Sintra, Cabo da Roca e Cascais',es:'Sintra, Cabo da Roca y Cascais'}},
 {id:'fatima',price:95,duration:'9–10 h',name:{en:'Fátima, Nazaré & Óbidos',pt:'Fátima, Nazaré e Óbidos',es:'Fátima, Nazaré y Óbidos'}},
 {id:'evora',price:105,duration:'8–9 h',name:{en:'Évora & Alentejo',pt:'Évora e Alentejo',es:'Évora y Alentejo'}}
];
const LANGUAGES=['en','es','pt'];
const SITE_URL=(process.env.SITE_URL||'https://aboutculturethings.com').replace(/\/$/,'');
const stripe=process.env.STRIPE_SECRET_KEY&&!/placeholder/i.test(process.env.STRIPE_SECRET_KEY)?new Stripe(process.env.STRIPE_SECRET_KEY):null;
function text(v,max=500){return String(v||'').trim().slice(0,max)}
function email(v){const x=text(v,254).toLowerCase();return/^\S+@\S+\.\S+$/.test(x)?x:''}
function reference(){return'ACT-'+crypto.randomBytes(8).toString('hex').toUpperCase()}
function tourById(id){return TOURS.find(t=>t.id===id)}
function minDate(){const d=new Date(Date.now()+24*36e5);return d.toISOString().slice(0,10)}
function validDate(v){return/^\d{4}-\d{2}-\d{2}$/.test(v||'')&&v>=minDate()}
function calendarInvite(b){const d=(b.date||'').replace(/-/g,'');const esc=v=>String(v||'').replace(/([,;\\])/g,'\\$1').replace(/\n/g,'\\n');return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//About Culture Things//Bookings//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','BEGIN:VEVENT',`UID:${esc(b.reference)}@aboutculturethings.com`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z')}`,`DTSTART;TZID=Europe/Lisbon:${d}T083000`,`DTEND;TZID=Europe/Lisbon:${d}T173000`,`SUMMARY:${esc(b.tourName)} · ${esc(b.customerName)}`,`DESCRIPTION:${esc(`${b.persons} guests · ${b.tourLanguage.toUpperCase()} · ${b.customerEmail} · ${b.customerPhone||''} · ${b.requests||''}`)}`,`LOCATION:${esc(b.pickup)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n')}
async function sendConfirmation(b){const host=process.env.SMTP_HOST||process.env.EMAIL_HOST,user=process.env.SMTP_USER||process.env.EMAIL_USER,pass=process.env.SMTP_PASS||process.env.EMAIL_PASS;if(!host||!user||!pass||/placeholder/i.test(pass))return false;const transport=nodemailer.createTransport({host,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465||String(process.env.SMTP_SECURE)==='true',auth:{user,pass}});const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const html=`<div style="max-width:620px;margin:auto;font:15px/1.6 Arial;color:#1f2b28"><div style="padding:28px;background:#153b32;color:#fff"><h1 style="margin:0;font:30px Georgia">About Culture Things</h1><p>Booking confirmed · ${esc(b.reference)}</p></div><div style="padding:28px;border:1px solid #ddd"><p>Dear ${esc(b.customerName)},</p><p>Your payment is confirmed. We will contact you before the tour if we need to coordinate pickup details.</p><table style="width:100%"><tr><td>Tour</td><td><strong>${esc(b.tourName)}</strong></td></tr><tr><td>Date</td><td>${esc(b.date)}</td></tr><tr><td>Guests</td><td>${b.persons}</td></tr><tr><td>Language</td><td>${esc(b.tourLanguage.toUpperCase())}</td></tr><tr><td>Pickup & return</td><td>${esc(b.pickup)}</td></tr><tr><td>Total paid</td><td><strong>€${b.totalPrice} EUR</strong></td></tr></table><p>Free cancellation is available until 48 hours before departure.</p><p>RNAAT Nº 726/2024</p></div></div>`;await transport.sendMail({from:process.env.SMTP_FROM||user,to:b.customerEmail,bcc:process.env.ADMIN_EMAIL||process.env.NOTIFICATION_EMAIL||'aboutculturethings@gmail.com',subject:`Booking confirmed ${b.reference} · ${b.tourName}`,html,attachments:[{filename:`${b.reference}.ics`,content:calendarInvite(b),contentType:'text/calendar; charset=utf-8; method=PUBLISH'}]});return true}
function base64url(input){return Buffer.from(input).toString('base64').replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function calendarConfigured(){return Boolean(process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL&&process.env.GOOGLE_PRIVATE_KEY&&process.env.GOOGLE_CALENDAR_ID)}
async function googleAccessToken(){if(!calendarConfigured())return null;const now=Math.floor(Date.now()/1000);const header=base64url(JSON.stringify({alg:'RS256',typ:'JWT'}));const claim=base64url(JSON.stringify({iss:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,scope:'https://www.googleapis.com/auth/calendar',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600}));const unsigned=`${header}.${claim}`;const privateKey=process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g,'\n');const signature=crypto.sign('RSA-SHA256',Buffer.from(unsigned),privateKey);const assertion=`${unsigned}.${base64url(signature)}`;const body=new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok)throw new Error(`Google auth failed (${r.status})`);return (await r.json()).access_token}
async function createCalendarEvent(b){if(!calendarConfigured())return null;const token=await googleAccessToken();const start=`${b.date}T08:30:00`;const endHour=b.tourName&&/Fátima|Fatima/i.test(b.tourName)?18:30:00:17:30:00;const event={summary:`PAID · ${b.tourName} · ${b.customerName}`,location:b.pickup,description:[`Booking: ${b.reference}`,`Guests: ${b.persons}`,`Language: ${String(b.tourLanguage||'').toUpperCase()}`,`Customer: ${b.customerName}`,`Email: ${b.customerEmail}`,`Phone / WhatsApp: ${b.customerPhone||'-'}`,`Pickup: ${b.pickup}`,`Paid: €${b.totalPrice} ${b.currency||'EUR'}`,b.requests?`Notes: ${b.requests}`:'',`RNAAT Nº 726/2024`].filter(Boolean).join('\n'),start:{dateTime:start,timeZone:'Europe/Lisbon'},end:{dateTime:`${b.date}T${endHour}`,timeZone:'Europe/Lisbon'},reminders:{useDefault:false,overrides:[{method:'popup',minutes:1440},{method:'popup',minutes:120}]},extendedProperties:{private:{bookingReference:b.reference}}};const calendarId=encodeURIComponent(process.env.GOOGLE_CALENDAR_ID);const r=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(event)});if(!r.ok){const detail=await r.text();throw new Error(`Google Calendar failed (${r.status}): ${detail.slice(0,240)}`)}return await r.json()}
function bookingFromSession(s){const m=s.metadata||{};return{reference:m.reference,tourName:m.tourName,date:m.date,persons:Number(m.persons||0),tourLanguage:m.tourLanguage||'',pickup:m.pickup||'',requests:m.requests||'',customerName:m.customerName||'',customerEmail:s.customer_details?.email||s.customer_email||m.customerEmail||'',customerPhone:m.customerPhone||'',totalPrice:Number(s.amount_total||0)/100,currency:String(s.currency||'eur').toUpperCase(),status:s.payment_status==='paid'?'confirmed':'awaiting_payment'}}
module.exports={TOURS,LANGUAGES,SITE_URL,stripe,text,email,reference,tourById,minDate,validDate,sendConfirmation,bookingFromSession,calendarConfigured,createCalendarEvent};
