/** About Culture Things — booking checkout */
(function(){
let overlay=null,lang='en',serverConfig=null;
const tx={
 en:{title:'Book Your Experience',tour:'Experience',date:'Date',guests:'Guests',contact:'Your details',name:'Full name',email:'Email',phone:'Phone (optional)',payment:'Payment',terms:'I accept the cancellation policy (free cancellation up to 48h before departure).',continue:'Continue',pay:'Continue to payment',back:'Back',total:'Total',meeting:'Meeting point',shared:'Shared small-group departure. Maximum 8 guests per road-tour vehicle.',error:'We could not complete the booking. Please try again.',stripeOff:'Card payment is temporarily unavailable. Please choose another payment method.'},
 es:{title:'Reserva tu experiencia',tour:'Experiencia',date:'Fecha',guests:'Personas',contact:'Tus datos',name:'Nombre completo',email:'Email',phone:'Teléfono (opcional)',payment:'Pago',terms:'Acepto la política de cancelación (cancelación gratuita hasta 48h antes).',continue:'Continuar',pay:'Continuar al pago',back:'Atrás',total:'Total',meeting:'Punto de encuentro',shared:'Salida compartida en grupo reducido. Máximo 8 personas por vehículo.',error:'No pudimos completar la reserva. Inténtalo nuevamente.',stripeOff:'El pago con tarjeta no está disponible temporalmente. Elige otro método.'},
 pt:{title:'Reserve a sua experiência',tour:'Experiência',date:'Data',guests:'Pessoas',contact:'Os seus dados',name:'Nome completo',email:'Email',phone:'Telefone (opcional)',payment:'Pagamento',terms:'Aceito a política de cancelamento (cancelamento gratuito até 48h antes).',continue:'Continuar',pay:'Continuar para pagamento',back:'Voltar',total:'Total',meeting:'Ponto de encontro',shared:'Saída partilhada em grupo reduzido. Máximo 8 pessoas por veículo.',error:'Não foi possível concluir a reserva. Tente novamente.',stripeOff:'O pagamento por cartão está temporariamente indisponível. Escolha outro método.'}
};
function text(){return tx[lang]||tx.en}
function tours(){return (window.TOURS_CONFIG&&window.TOURS_CONFIG.tours||[]).filter(x=>x.active)}
function minDate(){let d=new Date(Date.now()+24*3600000);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function price(t,n){return t.pricingType==='per_group'?t.price:t.price*(parseInt(n,10)||1)}
async function loadServerConfig(){try{let r=await fetch('/api/tours',{headers:{Accept:'application/json'}});if(!r.ok)throw Error();serverConfig=await r.json()}catch(e){serverConfig=null}}
function paymentMethods(){let p=serverConfig&&serverConfig.paymentMethods;return p||{stripe:false,mbway:true,wise:true,revolut:true,sepa:true}}
function render(){
 const t=text(),list=tours();
 const options=list.map(x=>{let n=typeof x.name==='object'?(x.name[lang]||x.name.en):x.name;return `<option value="${x.id}">${n} — €${x.price} ${x.pricingType==='per_person'?(lang==='es'?'por persona':lang==='pt'?'por pessoa':'per guest'):'per group'}</option>`}).join('');
 overlay=document.createElement('div');overlay.id='act-booking-overlay';overlay.className='act-booking-overlay';
 overlay.innerHTML=`<div class="act-booking-drawer" role="dialog" aria-modal="true" aria-labelledby="act-title"><div class="act-drawer-header"><div><p class="act-drawer-kicker">About Culture Things</p><h2 id="act-title" class="act-drawer-title">${t.title}</h2></div><button class="act-drawer-close" id="act-close" type="button" aria-label="Close">×</button></div><div class="act-drawer-body"><div id="act-error" class="act-alert-error" style="display:none"></div>
 <form id="act-form"><div class="act-form-group"><label>${t.tour}</label><select id="act-tour" class="act-input" required>${options}</select></div><div class="act-form-row"><div class="act-form-group flex-2"><label>${t.date}</label><input id="act-date" class="act-input" type="date" min="${minDate()}" required></div><div class="act-form-group flex-1"><label>${t.guests}</label><select id="act-guests" class="act-input"></select></div></div><div class="act-meeting-box"><strong>${t.meeting}</strong><p id="act-meeting">09:00 — Hard Rock Cafe Lisbon</p><span class="act-meeting-note">${t.shared}</span></div><div class="act-price-breakdown"><div class="act-price-line act-total-line"><span>${t.total}</span><span id="act-total" class="act-gold-total">€0</span></div></div>
 <h3>${t.contact}</h3><div class="act-form-group"><label>${t.name} *</label><input id="act-name" class="act-input" autocomplete="name" required></div><div class="act-form-group"><label>${t.email} *</label><input id="act-email" class="act-input" type="email" autocomplete="email" required></div><div class="act-form-group"><label>${t.phone}</label><input id="act-phone" class="act-input" type="tel" autocomplete="tel"></div>
 <h3>${t.payment}</h3><div id="act-payments" class="act-payment-options"></div><div class="act-form-group act-terms-check"><label class="act-checkbox-label"><input id="act-terms" type="checkbox" required><span>${t.terms}</span></label></div><div class="act-drawer-footer"><button id="act-submit" class="act-btn-gold act-w-full" type="submit">${t.pay}</button></div></form></div></div>`;
 document.body.appendChild(overlay);bind();
}
function buildGuests(){let tour=tours().find(x=>x.id===document.getElementById('act-tour').value)||tours()[0],s=document.getElementById('act-guests'),current=parseInt(s.value,10)||1,max=tour.maxPersons||8,min=tour.minPersons||1;s.innerHTML='';for(let i=min;i<=max;i++){let o=document.createElement('option');o.value=i;o.textContent=String(i);s.appendChild(o)}s.value=String(Math.min(Math.max(current,min),max));updateTotal()}
function updateTotal(){let tour=tours().find(x=>x.id===document.getElementById('act-tour').value),n=document.getElementById('act-guests').value;document.getElementById('act-total').textContent='€'+price(tour,n)}
function buildPayments(){let p=paymentMethods(),box=document.getElementById('act-payments'),labels={stripe:'Credit / debit card',mbway:'MB WAY',wise:'Wise',revolut:'Revolut',sepa:'SEPA bank transfer'},enabled=Object.keys(labels).filter(k=>p[k]);box.innerHTML=enabled.map((k,i)=>`<label class="act-payment-card${i===0?' active':''}"><input type="radio" name="act-payment" value="${k}" ${i===0?'checked':''}><div><strong>${labels[k]}</strong><p>${k==='stripe'?'Secure online payment':'Booking confirmed after payment verification'}</p></div></label>`).join('');box.querySelectorAll('.act-payment-card').forEach(c=>c.addEventListener('click',()=>{box.querySelectorAll('.act-payment-card').forEach(x=>x.classList.remove('active'));c.classList.add('active');c.querySelector('input').checked=true}))}
function showError(m){let e=document.getElementById('act-error');e.textContent=m;e.style.display='block';e.scrollIntoView({behavior:'smooth',block:'nearest'})}
async function submit(e){e.preventDefault();let t=text(),btn=document.getElementById('act-submit'),tour=tours().find(x=>x.id===document.getElementById('act-tour').value),method=document.querySelector('input[name="act-payment"]:checked');if(!tour||!method)return showError(t.error);let payload={tourId:tour.id,date:document.getElementById('act-date').value,persons:document.getElementById('act-guests').value,name:document.getElementById('act-name').value.trim(),email:document.getElementById('act-email').value.trim(),phone:document.getElementById('act-phone').value.trim(),paymentMethod:method.value,lang};if(!payload.date||!payload.name||!payload.email||!document.getElementById('act-terms').checked)return showError(t.error);btn.disabled=true;btn.textContent='…';try{let endpoint=method.value==='stripe'?'/api/create-checkout-session':'/api/bookings';let r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});let data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.error||t.error);if(method.value==='stripe'){if(!data.checkoutUrl)throw Error(t.stripeOff);window.location.assign(data.checkoutUrl);return}if(!data.success||!data.booking)throw Error(data.error||t.error);let b=data.booking;document.querySelector('.act-drawer-body').innerHTML=`<div class="act-confirm-badge">✓</div><h3 class="act-confirm-title">${lang==='es'?'Reserva recibida':lang==='pt'?'Reserva recebida':'Booking received'}</h3><p class="act-confirm-msg">${lang==='es'?'Te enviaremos las instrucciones de pago y confirmación por email.':lang==='pt'?'Enviaremos as instruções de pagamento e confirmação por email.':'Payment instructions and confirmation will be sent by email.'}</p><div class="act-ref-box"><span>Reference</span><strong class="act-gold-ref">${b.reference}</strong></div><button class="act-btn-gold act-w-full" id="act-finish" type="button">OK</button>`;document.getElementById('act-finish').onclick=close}catch(err){showError(err.message||t.error);btn.disabled=false;btn.textContent=t.pay}}
function bind(){document.getElementById('act-close').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};document.getElementById('act-tour').onchange=buildGuests;document.getElementById('act-guests').onchange=updateTotal;document.getElementById('act-form').onsubmit=submit;buildGuests();buildPayments()}
function close(){if(overlay){overlay.remove();overlay=null}document.body.classList.remove('booking-open')}
async function open(tourId){lang=(document.documentElement.lang||'en').slice(0,2);if(!tx[lang])lang='en';if(overlay)close();await loadServerConfig();render();if(tourId&&document.getElementById('act-tour').querySelector(`option[value="${tourId}"]`)){document.getElementById('act-tour').value=tourId;buildGuests()}document.body.classList.add('booking-open')}
document.addEventListener('click',e=>{let trigger=e.target.closest('[data-open-booking]');if(trigger){e.preventDefault();open(trigger.getAttribute('data-tour-id')||trigger.dataset.tourId||'')}});
window.ACTBooking={open,close};
})();
