(function () {
  const root=document.getElementById('booking-root');
  let selectedTourId='sintra-coast', step=1, attemptId='', paymentConfigured=null, lastFocused=null;
  const availabilityCopy={en:'There are not enough places left for this date. Please choose another date or a smaller group.',pt:'Não há lugares suficientes nesta data. Escolha outra data ou um grupo menor.',es:'No quedan plazas suficientes para esta fecha. Elige otra fecha o un grupo más pequeño.',fr:'Il ne reste pas assez de places à cette date. Choisissez une autre date ou un groupe plus petit.',de:'Für dieses Datum sind nicht genügend Plätze frei. Wählen Sie ein anderes Datum oder eine kleinere Gruppe.'};
  const fallbackCopy={en:'Online payment is not available yet. Send this booking request by email',pt:'O pagamento online ainda não está disponível. Envie este pedido por email',es:'El pago online todavía no está disponible. Envía esta solicitud por email',fr:'Le paiement en ligne n’est pas encore disponible. Envoyez cette demande par e-mail',de:'Die Online-Zahlung ist noch nicht verfügbar. Senden Sie diese Anfrage per E-Mail'};
  const labels={
    en:{title:'Book your experience',steps:['Experience','Details','Contact','Payment'],choose:'Choose an experience and date',date:'Date',guests:'Guests',continue:'Continue',back:'Back',language:'Tour language',pickup:'Lisbon pickup address',pickupHint:'Hotel or accommodation name and full address. Exact pickup time is confirmed by email.',meeting:'This experience meets in central Sintra. The exact point is confirmed by email.',requests:'Children’s ages, accessibility or special requests',contact:'Your contact details',name:'Full name',email:'Email',phone:'Phone (optional)',review:'Review and pay',included:'Included',includedText:'Local guide, required insurance and the inclusions shown for your selected tour.',excluded:'Not included',excludedText:'Monument tickets, meals and personal expenses unless expressly stated.',policy:'I accept free cancellation until 48 hours before departure and the booking terms.',pay:'Continue to secure payment',currency:'You will be charged in EUR. Your bank may convert the amount.',summary:'Your booking',notSelected:'Not selected',error:'Please complete all required fields.',paymentError:'Secure payment could not be started. Please try again or email us.',processing:'Opening secure payment…'},
    pt:{title:'Reserve a sua experiência',steps:['Experiência','Detalhes','Contacto','Pagamento'],choose:'Escolha a experiência e a data',date:'Data',guests:'Pessoas',continue:'Continuar',back:'Voltar',language:'Idioma do tour',pickup:'Morada de recolha em Lisboa',pickupHint:'Nome e morada completa do hotel ou alojamento. A hora exata é confirmada por email.',meeting:'Esta experiência começa no centro de Sintra. O ponto exato é confirmado por email.',requests:'Idades das crianças, acessibilidade ou pedidos especiais',contact:'Os seus contactos',name:'Nome completo',email:'Email',phone:'Telefone (opcional)',review:'Rever e pagar',included:'Incluído',includedText:'Guia local, seguros obrigatórios e as inclusões indicadas no tour escolhido.',excluded:'Não incluído',excludedText:'Bilhetes, refeições e despesas pessoais salvo indicação expressa.',policy:'Aceito o cancelamento gratuito até 48 horas antes e os termos da reserva.',pay:'Continuar para pagamento seguro',currency:'A cobrança é feita em EUR. O seu banco poderá converter o valor.',summary:'A sua reserva',notSelected:'Por selecionar',error:'Preencha todos os campos obrigatórios.',paymentError:'Não foi possível iniciar o pagamento seguro. Tente novamente ou contacte-nos por email.',processing:'A abrir pagamento seguro…'},
    es:{title:'Reserva tu experiencia',steps:['Experiencia','Detalles','Contacto','Pago'],choose:'Elige experiencia y fecha',date:'Fecha',guests:'Personas',continue:'Continuar',back:'Atrás',language:'Idioma del tour',pickup:'Dirección de recogida en Lisboa',pickupHint:'Nombre y dirección completa del hotel o alojamiento. La hora exacta se confirma por email.',meeting:'Esta experiencia comienza en el centro de Sintra. El punto exacto se confirma por email.',requests:'Edades de niños, accesibilidad o peticiones especiales',contact:'Tus datos de contacto',name:'Nombre completo',email:'Email',phone:'Teléfono (opcional)',review:'Revisar y pagar',included:'Incluido',includedText:'Guía local, seguros obligatorios y las inclusiones indicadas para el tour elegido.',excluded:'No incluido',excludedText:'Entradas, comidas y gastos personales salvo indicación expresa.',policy:'Acepto la cancelación gratuita hasta 48 horas antes y las condiciones.',pay:'Continuar al pago seguro',currency:'El cobro se realiza en EUR. Tu banco puede convertir el importe.',summary:'Tu reserva',notSelected:'Sin seleccionar',error:'Completa todos los campos obligatorios.',paymentError:'No se pudo iniciar el pago seguro. Inténtalo de nuevo o escríbenos por email.',processing:'Abriendo pago seguro…'},
    fr:{title:'Réserver votre expérience',steps:['Expérience','Détails','Contact','Paiement'],choose:'Choisissez une expérience et une date',date:'Date',guests:'Personnes',continue:'Continuer',back:'Retour',language:'Langue de la visite',pickup:'Adresse de prise en charge à Lisbonne',pickupHint:'Nom et adresse complète de l’hôtel ou hébergement. L’heure exacte est confirmée par e-mail.',meeting:'Cette expérience commence au centre de Sintra. Le lieu exact est confirmé par e-mail.',requests:'Âge des enfants, accessibilité ou demandes particulières',contact:'Vos coordonnées',name:'Nom complet',email:'E-mail',phone:'Téléphone (facultatif)',review:'Vérifier et payer',included:'Inclus',includedText:'Guide local, assurances obligatoires et prestations indiquées pour la visite choisie.',excluded:'Non inclus',excludedText:'Billets, repas et dépenses personnelles sauf mention expresse.',policy:'J’accepte l’annulation gratuite jusqu’à 48 heures avant et les conditions.',pay:'Continuer vers le paiement sécurisé',currency:'Le paiement est débité en EUR. Votre banque peut convertir le montant.',summary:'Votre réservation',notSelected:'Non sélectionné',error:'Veuillez remplir tous les champs obligatoires.',paymentError:'Le paiement sécurisé n’a pas pu démarrer. Réessayez ou contactez-nous par e-mail.',processing:'Ouverture du paiement sécurisé…'},
    de:{title:'Erlebnis buchen',steps:['Erlebnis','Details','Kontakt','Zahlung'],choose:'Erlebnis und Datum wählen',date:'Datum',guests:'Gäste',continue:'Weiter',back:'Zurück',language:'Tour-Sprache',pickup:'Abholadresse in Lissabon',pickupHint:'Name und vollständige Adresse von Hotel oder Unterkunft. Die genaue Zeit bestätigen wir per E-Mail.',meeting:'Dieses Erlebnis beginnt im Zentrum von Sintra. Den genauen Treffpunkt bestätigen wir per E-Mail.',requests:'Alter der Kinder, Barrierefreiheit oder besondere Wünsche',contact:'Ihre Kontaktdaten',name:'Vollständiger Name',email:'E-Mail',phone:'Telefon (optional)',review:'Prüfen und bezahlen',included:'Enthalten',includedText:'Lokaler Guide, vorgeschriebene Versicherungen und die beim gewählten Erlebnis genannten Leistungen.',excluded:'Nicht enthalten',excludedText:'Eintrittskarten, Mahlzeiten und persönliche Ausgaben, sofern nicht ausdrücklich genannt.',policy:'Ich akzeptiere kostenlose Stornierung bis 48 Stunden vorher und die Buchungsbedingungen.',pay:'Weiter zur sicheren Zahlung',currency:'Die Belastung erfolgt in EUR. Ihre Bank kann den Betrag umrechnen.',summary:'Ihre Buchung',notSelected:'Nicht ausgewählt',error:'Bitte füllen Sie alle Pflichtfelder aus.',paymentError:'Die sichere Zahlung konnte nicht gestartet werden. Versuchen Sie es erneut oder schreiben Sie uns.',processing:'Sichere Zahlung wird geöffnet…'}
  };
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lang=()=>window.ACT_LANG||'en'; const L=()=>labels[lang()]||labels.en;
  const tours=()=>TOURS_CONFIG.tours.filter(t=>t.active); const tour=()=>tours().find(t=>t.id===selectedTourId)||tours()[0];
  function minDate(){const d=new Date(Date.now()+TOURS_CONFIG.minAdvanceBookingHours*36e5);if(d.getHours()>=9)d.setDate(d.getDate()+1);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');}
  function values(){const get=id=>root.querySelector('#'+id);return {tourId:selectedTourId,date:get('book-date')?.value||'',persons:Number(get('book-guests')?.value||1),tourLanguage:get('book-language')?.value||'en',pickup:get('book-pickup')?.value.trim()||'',requests:get('book-requests')?.value.trim()||'',name:get('book-name')?.value.trim()||'',email:get('book-email')?.value.trim()||'',phone:get('book-phone')?.value.trim()||''};}
  function render(selected){if(selected)selectedTourId=selected;const l=L(),c=SITE_CONTENT[lang()]||SITE_CONTENT.en,t=tour();root.innerHTML=`<div class="booking-overlay" role="presentation"><div class="booking-dialog" role="dialog" aria-modal="true" aria-labelledby="booking-title"><section class="booking-main"><div class="booking-head"><div><p class="eyebrow">About Culture Things</p><h2 id="booking-title">${esc(l.title)}</h2></div><button class="booking-close" type="button" aria-label="Close">×</button></div><div class="booking-progress">${l.steps.map((x,i)=>`<span class="${step===i+1?'active':''}" ${step===i+1?'aria-current="step"':''}>${i+1}. ${esc(x)}</span>`).join('')}</div><div id="booking-error" class="form-error" role="alert" aria-live="polite" hidden></div>
      <form id="booking-form" novalidate>
        <section class="booking-step ${step===1?'active':''}" data-step="1"><h3>${esc(l.choose)}</h3><div class="choice-grid">${tours().map(x=>`<label class="choice"><input type="radio" name="tour" value="${esc(x.id)}" ${x.id===selectedTourId?'checked':''}><strong>${esc(x.name[lang()]||x.name.en)}</strong><span>${esc(x.duration)} · €${x.price} ${esc(c.t.perPerson)}</span></label>`).join('')}</div><div class="field-grid" style="margin-top:1.2rem"><div class="field"><label for="book-date">${esc(l.date)} *</label><input id="book-date" type="date" min="${minDate()}" required></div><div class="field"><label for="book-guests">${esc(l.guests)} *</label><select id="book-guests">${Array.from({length:t.maxPersons},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('')}</select></div></div></section>
        <section class="booking-step ${step===2?'active':''}" data-step="2"><h3>${esc(l.steps[1])}</h3><div class="field"><label for="book-language">${esc(l.language)} *</label><select id="book-language"><option value="en">English</option><option value="es">Español</option><option value="pt">Português</option></select></div>${t.pickupType==='lisbon'?`<div class="field"><label for="book-pickup">${esc(l.pickup)} *</label><textarea id="book-pickup" required></textarea><small>${esc(l.pickupHint)}</small></div>`:`<input id="book-pickup" type="hidden" value="Central Sintra meeting point"><p>${esc(l.meeting)}</p>`}<div class="field"><label for="book-requests">${esc(l.requests)}</label><textarea id="book-requests"></textarea></div></section>
        <section class="booking-step ${step===3?'active':''}" data-step="3"><h3>${esc(l.contact)}</h3><div class="field"><label for="book-name">${esc(l.name)} *</label><input id="book-name" autocomplete="name" required></div><div class="field"><label for="book-email">${esc(l.email)} *</label><input id="book-email" type="email" autocomplete="email" required></div><div class="field"><label for="book-phone">${esc(l.phone)}</label><input id="book-phone" type="tel" autocomplete="tel"></div></section>
        <section class="booking-step ${step===4?'active':''}" data-step="4"><h3>${esc(l.review)}</h3><p><strong>${esc(l.included)}:</strong> ${esc(l.includedText)}</p><p><strong>${esc(l.excluded)}:</strong> ${esc(l.excludedText)}</p><label class="terms"><input id="book-terms" type="checkbox" required><span>${esc(l.policy)} <a href="/terms/?lang=${esc(lang())}" target="_blank" rel="noopener" aria-label="Booking terms">↗</a></span></label><p class="currency-note">${esc(l.currency)}</p></section>
        <div class="booking-actions">${step>1?`<button type="button" class="button" id="book-back">${esc(l.back)}</button>`:''}<button type="submit" class="button" id="book-next">${esc(step===4?l.pay:l.continue)}</button></div>
      </form></section><aside class="booking-aside"><p class="summary-title">${esc(l.summary)}</p><div class="summary-lines" id="booking-summary"></div><div class="summary-total"><span>Total</span><strong id="summary-total">€${t.price}</strong></div><p class="summary-note">${esc(l.currency)}</p><div class="booking-trust"><span>✓ ${esc((SITE_CONTENT[lang()]||SITE_CONTENT.en).t.trustThree)}</span><span>✓ ${esc((SITE_CONTENT[lang()]||SITE_CONTENT.en).t.guided)}</span><span>✓ Secure payment by Stripe</span></div></aside></div></div>`;
    bind(); updateSummary();
  }
  function preserve(){const v=values();sessionStorage.setItem('act-booking-draft',JSON.stringify(v));return v;}
  function restore(){try{return JSON.parse(sessionStorage.getItem('act-booking-draft'))||{};}catch{return {};}}
  function hydrate(d){Object.entries({date:'book-date',persons:'book-guests',tourLanguage:'book-language',pickup:'book-pickup',requests:'book-requests',name:'book-name',email:'book-email',phone:'book-phone'}).forEach(([k,id])=>{const el=root.querySelector('#'+id);if(el&&d[k]!=null)el.value=d[k];});}
  function updateSummary(){const v=values(),t=tour(),l=L();root.querySelector('#booking-summary').innerHTML=`<div class="summary-line"><span>${esc(l.steps[0])}</span><strong>${esc(t.name[lang()]||t.name.en)}</strong></div><div class="summary-line"><span>${esc(l.date)}</span><strong>${esc(v.date||l.notSelected)}</strong></div><div class="summary-line"><span>${esc(l.guests)}</span><strong>${v.persons}</strong></div><div class="summary-line"><span>${esc(l.language)}</span><strong>${esc({en:'English',es:'Español',pt:'Português'}[v.tourLanguage])}</strong></div><div class="summary-line"><span>${esc(l.pickup)}</span><strong>${esc(v.pickup||l.notSelected)}</strong></div>`;root.querySelector('#summary-total').textContent='€'+(t.price*v.persons);}
  function showError(text){const el=root.querySelector('#booking-error');el.textContent=text;el.hidden=false;}
  function showPaymentFallback(v){showError(fallbackCopy[lang()]||fallbackCopy.en);const el=root.querySelector('#booking-error'),t=tour(),subject='Booking request · '+(t.name[lang()]||t.name.en),body=['Experience: '+(t.name[lang()]||t.name.en),'Date: '+v.date,'Guests: '+v.persons,'Tour language: '+v.tourLanguage.toUpperCase(),'Name: '+v.name,'Email: '+v.email,'Pickup / meeting: '+v.pickup].join('\n');const link=document.createElement('a');link.href='mailto:aboutculturethings@gmail.com?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);link.textContent=' →';link.setAttribute('aria-label',fallbackCopy[lang()]||fallbackCopy.en);el.appendChild(link);}
  function valid(v){if(step===1)return v.date&&v.date>=minDate();if(step===2)return v.tourLanguage&&(tour().pickupType!=='lisbon'||v.pickup);if(step===3)return v.name&&/^\S+@\S+\.\S+$/.test(v.email);if(step===4)return root.querySelector('#book-terms').checked;return true;}
  function bind(){root.querySelector('.booking-close').onclick=close;root.querySelector('.booking-overlay').onclick=e=>{if(e.target===e.currentTarget)close();};root.querySelectorAll('input[name="tour"]').forEach(x=>x.onchange=()=>{const draft=preserve();selectedTourId=x.value;render();hydrate(draft);updateSummary();});root.querySelectorAll('input,select,textarea').forEach(x=>x.addEventListener('input',updateSummary));const back=root.querySelector('#book-back');if(back)back.onclick=()=>{const d=preserve();step--;render();hydrate(d);updateSummary();};root.querySelector('#booking-form').onsubmit=submit;}
  async function submit(e){e.preventDefault();const v=values();if(!valid(v)){showError(L().error);return;}if(step===1){try{const res=await fetch('/api/availability?tourId='+encodeURIComponent(v.tourId)+'&date='+encodeURIComponent(v.date));const data=await res.json();if(res.ok&&data.availableSeats<v.persons){showError(availabilityCopy[lang()]||availabilityCopy.en);return;}}catch(error){/* Final checkout validation remains authoritative. */}}if(step<4){preserve();step++;render();hydrate(v);updateSummary();return;}if(paymentConfigured===false){showPaymentFallback(v);return;}const button=root.querySelector('#book-next');button.disabled=true;button.textContent=L().processing;if(!attemptId)attemptId=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random());try{const res=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':attemptId},body:JSON.stringify({...v,lang:lang(),bookingAttemptId:attemptId})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.checkoutUrl)throw new Error(data.error||'payment');location.assign(data.checkoutUrl);}catch(err){button.disabled=false;button.textContent=L().pay;showError(L().paymentError);}}
  function close(){root.innerHTML='';document.body.classList.remove('no-scroll');step=1;attemptId='';sessionStorage.removeItem('act-booking-draft');if(lastFocused&&lastFocused.focus)lastFocused.focus();lastFocused=null;}
  window.openBooking=function(id){lastFocused=document.activeElement;selectedTourId=tours().some(t=>t.id===id)?id:selectedTourId;step=1;render();document.body.classList.add('no-scroll');requestAnimationFrame(()=>root.querySelector('.booking-close')?.focus());};
  window.refreshBooking=function(){if(root.innerHTML){const d=preserve();render();hydrate(d);updateSummary();}};
  addEventListener('keydown',e=>{if(e.key==='Escape'&&root.innerHTML){close();return;}if(e.key==='Tab'&&root.innerHTML){const focusable=[...root.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled])')].filter(el=>el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  addEventListener('scroll',()=>document.getElementById('site-header').classList.toggle('is-scrolled',scrollY>20),{passive:true});
  document.getElementById('site-header').classList.toggle('is-scrolled',scrollY>20);
  fetch('/api/health').then(response=>response.ok?response.json():null).then(data=>{paymentConfigured=Boolean(data&&data.paymentConfigured);}).catch(()=>{paymentConfigured=false;});
  const params=new URLSearchParams(location.search);if(params.get('book'))setTimeout(()=>openBooking(params.get('book')),0);
}());
