(()=>{let blocked=new Set(),loaded=false;async function refresh(){try{const r=await fetch('/api/availability',{cache:'no-store'});if(!r.ok)throw new Error('availability');const d=await r.json();blocked=new Set(d.blockedDates||[]);loaded=true;return true}catch{return false}}function message(){const l=document.documentElement.lang;return l==='pt'?'Esta data não está disponível. Escolha outro dia.':l==='es'?'Esta fecha no está disponible. Elige otro día.':'This date is not available. Please choose another day.'}function validate(input){if(!input||input.name!=='date')return true;const bad=blocked.has(input.value);input.setCustomValidity(bad?message():'');if(bad)input.reportValidity();return !bad}document.addEventListener('change',e=>{if(e.target.matches('input[name="date"]'))validate(e.target)});document.addEventListener('submit',async e=>{const input=e.target.querySelector?.('input[name="date"]');if(!input)return;await refresh();if(!validate(input)){e.preventDefault();e.stopImmediatePropagation()}},true);refresh();document.addEventListener('click',e=>{if(e.target.closest('[data-open-tour]'))setTimeout(refresh,100)});

// Keep product wording intentionally clear without labelling the experience as private or shared.
const clarity={
 en:{heroKicker:'Local guided day tours in Portugal',heroTitle:'Portugal, personally guided.',heroText:'Guided day tours with hotel pickup and return, local knowledge and simple secure booking.',trust1:'Local guided experience',trust2:'2–4 travellers per booking',why3Text:'Personal attention for your booking, with the right guide and vehicle arranged for the day.',footerText:'Local guided day tours across Portugal.',minGuests:'2–4 travellers per booking',back:'Back to all tours',what:'What you are booking',points:['A guided day tour for your booking of 2–4 travellers','Pickup and return at your accommodation in Lisbon, Sintra or Cascais','The displayed price is per person; your group total updates before payment','Tour language: English, Spanish or Portuguese','Monument tickets and meals are not included unless explicitly stated','Secure Stripe payment in EUR · Free cancellation up to 48 hours'],groupTotal:'Total for your booking'},
 pt:{heroKicker:'Tours guiados de um dia em Portugal',heroTitle:'Portugal, com acompanhamento local.',heroText:'Tours guiados com recolha e regresso ao alojamento, conhecimento local e reserva simples e segura.',trust1:'Experiência com guia local',trust2:'2–4 viajantes por reserva',why3Text:'Atenção pessoal à sua reserva, com o guia e o veículo adequados organizados para o dia.',footerText:'Tours guiados de um dia por Portugal.',minGuests:'2–4 viajantes por reserva',back:'Voltar a todos os tours',what:'O que está a reservar',points:['Um tour guiado de um dia para a sua reserva de 2–4 viajantes','Recolha e regresso ao alojamento em Lisboa, Sintra ou Cascais','O preço apresentado é por pessoa; o total do grupo atualiza antes do pagamento','Idioma do tour: inglês, espanhol ou português','Bilhetes de monumentos e refeições não estão incluídos, salvo indicação expressa','Pagamento Stripe seguro em EUR · Cancelamento gratuito até 48 horas'],groupTotal:'Total da sua reserva'},
 es:{heroKicker:'Tours guiados de un día por Portugal',heroTitle:'Portugal, con acompañamiento local.',heroText:'Tours guiados con recogida y regreso al alojamiento, conocimiento local y reserva sencilla y segura.',trust1:'Experiencia con guía local',trust2:'2–4 viajeros por reserva',why3Text:'Atención personal para tu reserva, organizando el guía y el vehículo adecuados para el día.',footerText:'Tours guiados de un día por Portugal.',minGuests:'2–4 viajeros por reserva',back:'Volver a todos los tours',what:'Qué estás reservando',points:['Un tour guiado de un día para tu reserva de 2–4 viajeros','Recogida y regreso en tu alojamiento de Lisboa, Sintra o Cascais','El precio mostrado es por persona; el total del grupo se actualiza antes del pago','Idioma del tour: inglés, español o portugués','Las entradas a monumentos y las comidas no están incluidas salvo indicación expresa','Pago seguro con Stripe en EUR · Cancelación gratuita hasta 48 horas'],groupTotal:'Total de tu reserva'},
 fr:{heroKicker:'Excursions guidées à la journée au Portugal',heroTitle:'Le Portugal, accompagné localement.',heroText:'Excursions guidées avec prise en charge et retour à votre hébergement, connaissances locales et réservation simple et sécurisée.',trust1:'Expérience avec guide local',trust2:'2–4 voyageurs par réservation',why3Text:'Une attention personnalisée pour votre réservation, avec le guide et le véhicule adaptés à la journée.',footerText:'Excursions guidées à la journée au Portugal.',minGuests:'2–4 voyageurs par réservation',back:'Retour à toutes les excursions',what:'Ce que vous réservez',points:['Une excursion guidée à la journée pour votre réservation de 2 à 4 voyageurs','Prise en charge et retour à votre hébergement à Lisbonne, Sintra ou Cascais','Le prix affiché est par personne; le total du groupe est mis à jour avant le paiement','Langue de la visite: anglais, espagnol ou portugais','Les billets des monuments et les repas ne sont pas inclus sauf mention expresse','Paiement Stripe sécurisé en EUR · Annulation gratuite jusqu’à 48 heures'],groupTotal:'Total de votre réservation'},
 de:{heroKicker:'Geführte Tagestouren in Portugal',heroTitle:'Portugal, persönlich begleitet.',heroText:'Geführte Tagestouren mit Abholung und Rückfahrt zur Unterkunft, lokalem Wissen und einfacher sicherer Buchung.',trust1:'Erlebnis mit lokalem Guide',trust2:'2–4 Reisende pro Buchung',why3Text:'Persönliche Betreuung Ihrer Buchung mit dem passenden Guide und Fahrzeug für den Tag.',footerText:'Geführte Tagestouren durch Portugal.',minGuests:'2–4 Reisende pro Buchung',back:'Zurück zu allen Touren',what:'Das buchen Sie',points:['Eine geführte Tagestour für Ihre Buchung von 2 bis 4 Reisenden','Abholung und Rückfahrt an Ihrer Unterkunft in Lissabon, Sintra oder Cascais','Der angezeigte Preis gilt pro Person; der Gesamtpreis wird vor der Zahlung aktualisiert','Tour-Sprache: Englisch, Spanisch oder Portugiesisch','Eintrittskarten und Mahlzeiten sind nicht enthalten, sofern nicht ausdrücklich angegeben','Sichere Stripe-Zahlung in EUR · Kostenlose Stornierung bis 48 Stunden'],groupTotal:'Gesamtpreis Ihrer Buchung'}
};
function language(){const l=document.documentElement.lang;return clarity[l]?l:'en'}
function copyClarity(){const l=language(),v=clarity[l];if(typeof COPY!=='undefined'&&COPY[l]){Object.assign(COPY[l],{heroKicker:v.heroKicker,heroTitle:v.heroTitle,heroText:v.heroText,trust1:v.trust1,trust2:v.trust2,why3Text:v.why3Text,footerText:v.footerText,minGuests:v.minGuests});if(Array.isArray(COPY[l].faq)){COPY[l].faq=COPY[l].faq.map(([q,a])=>{if(/How many|Quantas pessoas|Cuántas personas|Combien de personnes|Wie viele Personen/i.test(q)){const answer=l==='pt'?'Cada reserva é para 2 a 4 viajantes. O mesmo dia pode continuar disponível para outras reservas.':l==='es'?'Cada reserva es para 2 a 4 viajeros. La misma fecha puede seguir disponible para otras reservas.':l==='fr'?'Chaque réservation est pour 2 à 4 voyageurs. La même date peut rester disponible pour d’autres réservations.':l==='de'?'Jede Buchung gilt für 2 bis 4 Reisende. Derselbe Tag kann für weitere Buchungen verfügbar bleiben.':'Each booking is for 2 to 4 travellers. The same date may remain available for other bookings.';return[q,answer]}return[q,a]})}}}
try{if(typeof guestOptions==='function')guestOptions=()=>[2,3,4].map(n=>`<option value="${n}">${n}</option>`).join('')}catch{}
copyClarity();try{if(typeof applyCopy==='function')applyCopy()}catch{}

const style=document.createElement('style');style.textContent=`
.clarity-back{display:inline-flex;align-items:center;gap:.35rem;margin:1rem 1.25rem 0;padding:.62rem .85rem;border:1px solid rgba(18,61,51,.16);border-radius:999px;background:#fff;color:#17352e;font:600 .84rem/1.1 'DM Sans',sans-serif;cursor:pointer}
.clarity-back:hover{background:#f5f7f6}.purchase-clarity{margin:1.25rem 0;padding:1rem 1.05rem;border:1px solid rgba(18,61,51,.12);border-radius:18px;background:#f7f9f8}.purchase-clarity h3{margin:0 0 .65rem;font-size:1rem}.purchase-clarity ul{margin:0;padding-left:1.15rem;display:grid;gap:.45rem}.purchase-clarity li{font-size:.92rem;line-height:1.45}.booking-total::after{content:' · ';}.booking-total[data-group-label]::after{content:' · ' attr(data-group-label);font-weight:500;opacity:.72}@media(max-width:700px){.clarity-back{margin:.8rem 1rem 0}.purchase-clarity{border-radius:14px}}
`;document.head.appendChild(style);

const dialogContent=document.getElementById('dialog-content');
function enhanceDialog(){if(!dialogContent||!dialogContent.children.length||dialogContent.querySelector('.clarity-back'))return;const v=clarity[language()];const back=document.createElement('button');back.type='button';back.className='clarity-back';back.innerHTML='← '+v.back;back.addEventListener('click',()=>{const d=document.getElementById('tour-dialog');if(d?.open)d.close();requestAnimationFrame(()=>document.getElementById('tours')?.scrollIntoView({behavior:'smooth',block:'start'}))});dialogContent.prepend(back);const form=dialogContent.querySelector('[data-booking-form]');if(form){const box=document.createElement('section');box.className='purchase-clarity';box.setAttribute('aria-label',v.what);box.innerHTML=`<h3>${v.what}</h3><ul>${v.points.map(p=>`<li>${p}</li>`).join('')}</ul>`;form.before(box);const total=form.querySelector('[data-booking-total]');if(total)total.dataset.groupLabel=v.groupTotal}}
if(dialogContent){new MutationObserver(enhanceDialog).observe(dialogContent,{childList:true,subtree:false});enhanceDialog()}
document.addEventListener('change',e=>{if(e.target===document.getElementById('language'))setTimeout(()=>{copyClarity();try{if(typeof applyCopy==='function')applyCopy()}catch{};enhanceDialog()},0)});
})();