/* Public business rules: keep product modality neutral and booking size consistent. */
(()=>{
  if(typeof COPY==='undefined')return;
  const neutral={
    en:{heroKicker:'Guided day tours across Portugal',heroTitle:'Portugal, personally guided.',heroText:'Day tours from Lisbon with hotel pickup, local guidance and easy secure booking.',trust1:'Locally guided experience',trust2:'2–4 travellers per booking',why3Title:'Personal attention',why3Text:'A carefully guided experience for your booking of 2 to 4 travellers.',footerText:'Guided day tours across Portugal.',minGuests:'2–4 travellers per booking',faqPeople:'Each booking is for 2 to 4 travellers.',bookingHelp:'Online bookings require at least 24 hours notice, calculated in Lisbon time.',cutoff:'This date can no longer be booked online. Please choose a later date.',unavailable:'This date is not available. Please choose another day.',flow:[['Choose a tour','Compare three clear options.'],['Select your date','Online booking requires at least 24 hours notice.'],['Pay securely','Receive confirmation after successful payment.']],availabilityQ:'How is date availability managed?',availabilityA:'Availability is managed operationally by About Culture Things and may change as each day is organised.'},
    pt:{heroKicker:'Tours guiados por Portugal',heroTitle:'Portugal, com acompanhamento local.',heroText:'Tours desde Lisboa, com recolha no alojamento, acompanhamento local e reserva simples e segura.',trust1:'Experiência acompanhada localmente',trust2:'2–4 viajantes por reserva',why3Title:'Atenção pessoal',why3Text:'Uma experiência acompanhada com cuidado para reservas de 2 a 4 viajantes.',footerText:'Tours guiados por Portugal.',minGuests:'2–4 viajantes por reserva',faqPeople:'Cada reserva é para 2 a 4 viajantes.',bookingHelp:'As reservas online requerem pelo menos 24 horas de antecedência, calculadas pela hora de Lisboa.',cutoff:'Esta data já não pode ser reservada online. Escolha uma data posterior.',unavailable:'Esta data não está disponível. Escolha outro dia.',flow:[['Escolha um tour','Compare três opções claras.'],['Selecione a data','A reserva online requer pelo menos 24 horas de antecedência.'],['Pague com segurança','Receba a confirmação após o pagamento.']],availabilityQ:'Como é gerida a disponibilidade?',availabilityA:'A disponibilidade é gerida operacionalmente pela About Culture Things e pode mudar à medida que cada dia é organizado.'},
    es:{heroKicker:'Tours guiados por Portugal',heroTitle:'Portugal, con acompañamiento local.',heroText:'Tours desde Lisboa, con recogida en el alojamiento, acompañamiento local y reserva sencilla y segura.',trust1:'Experiencia acompañada localmente',trust2:'2–4 viajeros por reserva',why3Title:'Atención personal',why3Text:'Una experiencia guiada con cuidado para reservas de 2 a 4 viajeros.',footerText:'Tours guiados por Portugal.',minGuests:'2–4 viajeros por reserva',faqPeople:'Cada reserva es para 2 a 4 viajeros.',bookingHelp:'Las reservas online requieren al menos 24 horas de antelación, calculadas según la hora de Lisboa.',cutoff:'Esta fecha ya no puede reservarse online. Elige una fecha posterior.',unavailable:'Esta fecha no está disponible. Elige otro día.',flow:[['Elige un tour','Compara tres opciones claras.'],['Selecciona la fecha','La reserva online requiere al menos 24 horas de antelación.'],['Paga con seguridad','Recibe la confirmación después del pago.']],availabilityQ:'¿Cómo se gestiona la disponibilidad?',availabilityA:'About Culture Things gestiona la disponibilidad de forma operativa y puede cambiar a medida que se organiza cada día.'},
    fr:{heroKicker:'Excursions guidées au Portugal',heroTitle:'Le Portugal, accompagné localement.',heroText:'Excursions depuis Lisbonne avec prise en charge à votre hébergement, accompagnement local et réservation simple et sécurisée.',trust1:'Expérience accompagnée localement',trust2:'2–4 voyageurs par réservation',why3Title:'Attention personnalisée',why3Text:'Une expérience guidée avec soin pour des réservations de 2 à 4 voyageurs.',footerText:'Excursions guidées au Portugal.',minGuests:'2–4 voyageurs par réservation',faqPeople:'Chaque réservation comprend 2 à 4 voyageurs.',bookingHelp:'Les réservations en ligne nécessitent au moins 24 heures de préavis, calculées selon l’heure de Lisbonne.',cutoff:'Cette date ne peut plus être réservée en ligne. Choisissez une date ultérieure.',unavailable:'Cette date n’est pas disponible. Choisissez un autre jour.',flow:[['Choisissez une excursion','Comparez trois options claires.'],['Sélectionnez la date','La réservation en ligne nécessite au moins 24 h de préavis.'],['Payez en toute sécurité','Recevez la confirmation après le paiement.']],availabilityQ:'Comment la disponibilité est-elle gérée ?',availabilityA:'La disponibilité est gérée opérationnellement par About Culture Things et peut évoluer selon l’organisation de chaque journée.'},
    de:{heroKicker:'Geführte Tagestouren durch Portugal',heroTitle:'Portugal, persönlich begleitet.',heroText:'Tagestouren ab Lissabon mit Abholung an Ihrer Unterkunft, lokaler Begleitung und einfacher sicherer Buchung.',trust1:'Lokal begleitetes Erlebnis',trust2:'2–4 Reisende pro Buchung',why3Title:'Persönliche Betreuung',why3Text:'Ein sorgfältig begleitetes Erlebnis für Buchungen mit 2 bis 4 Reisenden.',footerText:'Geführte Tagestouren durch Portugal.',minGuests:'2–4 Reisende pro Buchung',faqPeople:'Jede Buchung gilt für 2 bis 4 Reisende.',bookingHelp:'Online-Buchungen benötigen mindestens 24 Stunden Vorlauf, berechnet nach Lissabonner Zeit.',cutoff:'Dieses Datum kann online nicht mehr gebucht werden. Bitte wählen Sie ein späteres Datum.',unavailable:'Dieses Datum ist nicht verfügbar. Bitte wählen Sie einen anderen Tag.',flow:[['Tour auswählen','Drei klare Optionen vergleichen.'],['Datum wählen','Online-Buchungen benötigen mindestens 24 Stunden Vorlauf.'],['Sicher bezahlen','Bestätigung nach erfolgreicher Zahlung erhalten.']],availabilityQ:'Wie wird die Verfügbarkeit verwaltet?',availabilityA:'Die Verfügbarkeit wird von About Culture Things operativ verwaltet und kann sich bei der Organisation des jeweiligen Tages ändern.'}
  };
  Object.entries(neutral).forEach(([lng,n])=>{
    const x=COPY[lng];if(!x)return;
    Object.assign(x,{heroKicker:n.heroKicker,heroTitle:n.heroTitle,heroText:n.heroText,trust1:n.trust1,trust2:n.trust2,why3Title:n.why3Title,why3Text:n.why3Text,footerText:n.footerText,minGuests:n.minGuests,bookingHelp:n.bookingHelp,cutoff:n.cutoff,unavailable:n.unavailable,flow:n.flow});
    if(Array.isArray(x.faq)&&x.faq[2])x.faq[2][1]=n.faqPeople;
    if(Array.isArray(x.faq)&&x.faq[5])x.faq[5]=[n.availabilityQ,n.availabilityA];
  });
  try{guestOptions=()=>[2,3,4].map(n=>`<option value="${n}">${n}</option>`).join('')}catch{}
  try{bookingMinDate=()=>{const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Lisbon',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));const afterCutoff=(p.hour*60+p.minute)>(8*60+30);return new Date(Date.UTC(p.year,p.month-1,p.day+(afterCutoff?2:1))).toISOString().slice(0,10)}}catch{}
  const language=document.getElementById('language');
  if(language)language.dispatchEvent(new Event('change',{bubbles:true}));
})();
